---
services:
  LinkSharer:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
    container_name: LinkSharer-dev
    command: flask --app src/linksharer --debug run -p 5353 -h 0.0.0.0
    environment:
    - DEBUG=1
    volumes:
    - type: bind
      source: ../src
      target: /app/src
    - type: bind
      source: ../app/data
      target: /app/data
    - type: bind
      source: ../app/config
      target: /app/config
